TERMINOLOGY = {
  "LIMITS" : "A value that a function approaches the output for the given input values.",
  "DIFFERENTIATION" : "A calculus method for finding the rate of change of a function. ",
  "TANGENT LINE" : "A straight line that touches a curve at a single point.",
  "TRIGONOMETRY" : "Branch of mathematics concerned with relationships between angles and side lengths of triangles.",
  "DERIVATIVES" : " A contract between two parties that derives its value from an underlying asset.",
  "SLOPE" : "It is the rate of change of y with respect to x.",
  "INTEGRALS" : "Continuous analog of a sum, which is used to calculate areas, volumes, and their generalizations.",
  "RIGHT ANGLE" : "An angle of exactly 90 degrees or ⁠/2⁠ radians corresponding to a quarter turn.",
  "INERTIA" : "The tendency of an object to resist a change in its motion.",
  "VISCOSITY" : "Measure of a fluid's rate-dependent resistance to a change in shape or to movement of its neighboring portions relative to one another.",
  "BOUYANCY" : "The upward force that a fluid exerts on an object that is partially or fully submerged in it.",
  "MAGNITUDE" : "Defined as the maximum extent of size and the direction of an object.",
  "HYDRAULICS" : "The science of using liquids in motion for practical applications.",
  "STRAIN" : "A measure of how much a material deforms or changes shape when subjected to an applied force.",
  "SPRING" : "An elastic object that stores mechanical energy and releases it when the opposing force is removed.",
  "BERNOULLI'S PRINCIPLE" : "Key concept in fluid dynamics that relates pressure, density, speed and height.",
  "DIMENSIONS" : "The measurements of an object's length, width, and height. ",
  "ACCELERATION" : "Rate at which velocity changes with time, in terms of both speed and direction.",
  "COMBUSTION" : "A chemical reaction that occurs when fuel and oxygen combine and release energy.",
  "ENTROPY" : "A scientific concept that measures disorder, randomness, or uncertainty in a system.",
  "BEAM" : "A long, thick piece of wood, metal, or concrete that supports weight in a building or structure.",
  "INFRASTRUCTURE" : "The physical, social, and economic systems that support a society, region, or nation.",
  "CONCRETE" : "A composite material composed of aggregate bonded together with a fluid cement that cures to a solid over time.",
  "BRICK" : "A type of construction material used to build walls, pavements and other elements in masonry construction.",
  "CANTILEVER" : "A rigid structure that extends horizontally and is supported at only one end.",
  "SCAFFOLDING" : "A temporary structure that is typically made from metal poles and wood planks and used to support construction workers, inspectors, cleaners, and others who need to work at height.",
  "MASONRY" : "It consist of building structures from single units that are laid and bound together with mortar.",
  "MACADAM" : "A type of road construction that uses compacted layers of broken stone.",
  "CEMENT" : "A powder of alumina, silica, lime, iron oxide, and magnesium oxide burned together in a kiln and finely pulverized and used as an ingredient of mortar and concrete.",
  "BRIDGE" : "Structure that spans horizontally between supports, whose function is to carry vertical loads.",
  }
x = input ("Hi, I'm the Engineering Dictionary! What word do you want to know that is related to the engineering?")
print (TERMINOLOGY[x])
